server:
  port: 8083
spring:
  application:
    name: operationmanagement
  cloud:
    service-registry:
      auto-registration:
        enabled: true
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    enabled: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
      registerWithEureka: true
